### ISSUE TITLE
Add mobile meta tag

### ISSUE THREAD

**Issue by amyhenning** [sahumphreys59/take-one#1]
Hey Sarah,

Great job with your Splurty app!

Things look great with the Bootstrap styles and fonts you added - but on mobile things don't look as good as they could be. This is a common issue with a pretty simple fix.

Google search for how you can add a "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile. Once you find a tag to add, you can add it to your `application.html.erb` file here:

https://github.com/sahumphreys59/take-one/blob/master/app/views/layouts/application.html.erb#L7

Let me know in the comments once you figured that step out :)

Keep up the good work!

--Amy

**Comment by sahumphreys59** [comment]
I think I've fixed the mobile format.

**Comment by amyhenning** [comment]
Looks good! Great job searching for and implementing a solution - your app should now look better on mobile devices. :) Keep up the good work!
